### PR TITLE
Added/Fixed Right Click actions for nametag

### LINKED ISSUE #85: Nametags are not implemented

### PR DESCRIPTION
**Pull request by RORIdev**
Fixes #85

### CODE REVIEW

File: src/main/java/cn/nukkit/entity/mob/EntityMob.java [hunk 1]
```diff
@@ -20,12 +20,7 @@ public EntityMob(FullChunk chunk, CompoundTag nbt) {
     @Override
     public boolean onInteract(Player player, Item item, Vector3 clickedPos) {
         if (item.getId() == Item.NAME_TAG) {
-            if (item.hasCustomName()) {
-                this.setNameTag(item.getCustomName());
-                this.setNameTagVisible(true);
-                player.getInventory().removeItem(item);
-                return true;
-            }
```
Comment (joserobjr) [inline src/main/java/cn/nukkit/entity/mob/EntityMob.java]: I didn't know this code was there, I thought it wasn't implemented because the `ItemNameTag` didn't even exist lol. It's still a good PR through because it removed a duplicated code

File: src/main/java/cn/nukkit/entity/Entity.java [hunk 2]
```diff
@@ -1827,7 +1828,20 @@ public boolean isOnLadder() {
...
         return b.getId() == Block.LADDER;
     }
-
+    public boolean applyNametag(Player player, Item item)
+    {
+        if(item.hasCustomName())
+        {
+            this.setNameTag(item.getCustomName());
+            this.setNameTagVisible(true);
+            if(player.isSurvival()) { player.getInventory().removeItem(item); }
```
Comment (joserobjr) [inline src/main/java/cn/nukkit/entity/Entity.java]: I know that the original code used `removeItem`, I didn't actually test yet so I may be wrong but I think it would remove the entire stack, so if a player has 64 name tags in his hand, all them would be consumed. Maybe a `item.setCount(item.getCount() -1)` would be better.

File: src/main/java/cn/nukkit/Player.java [hunk 3]
```diff
@@ -3307,6 +3307,7 @@ public void onCompletion(Server server) {
 
                                         this.inventory.setItemInHand(item);
                                     }
+                                    //TODO : Trigger useOn in creative mode.
```
Comment (joserobjr) [inline src/main/java/cn/nukkit/Player.java]: I might do this TODO if nobody does it 😊

File: src/main/java/cn/nukkit/entity/Entity.java (hunk 2 above)
Comment (RORIdev) [reply src/main/java/cn/nukkit/entity/Entity.java]: Fixed on the next commit.

File: src/main/java/cn/nukkit/entity/mob/EntityMob.java (hunk 1 above)
Comment (joserobjr) [reply src/main/java/cn/nukkit/entity/mob/EntityMob.java]: Note: The code wasn't there hehe, it was added by this PR, I messed up :)

File: src/main/java/cn/nukkit/entity/Entity.java (hunk 2 above)
Comment (joserobjr) [reply src/main/java/cn/nukkit/entity/Entity.java]: I've made some improvements, I removed the direct item manipulation because the server already does that when `onInteract` returns `true`

File: src/main/java/cn/nukkit/Player.java (hunk 3 above)
Comment (joserobjr) [reply src/main/java/cn/nukkit/Player.java]: This is actually not needed, `Item.useOn` is to damage the item when it is used, since the player is in creative mode the item should not be damaged. The `Entity.onInteract()` method is still called by players in any game mode correctly, so I removed the TODO.

Comment (RORIdev) [reply src/main/java/cn/nukkit/Player.java]: I've noticed that after i've sent the second commit.
